# Site settings
title: Night Sweats Comedy
email: nightsweatscomedy@gmail.com
url: https://sangel10.github.io/nightsweats
baseurl: https://sangel10.github.io/nightsweats
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Night Sweats

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/nightsweatscomedy/
  - title: twitter
    url: https://twitter.com/night_sweats
  # - title: github
  #   url: https://github.com/sangel10

# Build settings
markdown: kramdown
permalink: pretty
